// frontend/app/routes/terminal/option-chain/components/OIBar.tsx
import { cx } from '$shared/ui/cx';
import type { Side } from '../chain-model';
import s from './OIBar.module.css';

interface Props {
  value?: number | undefined;
  max: number;
  side: Side;
  /**
   * Applied to the track.
   *
   * The page tints the bar per column with `td.ce.oi :global(.track)` in Svelte;
   * CSS Modules hashes that class, so the override comes in through here.
   */
  className?: string | undefined;
}

export default function OIBar({ value, max, side, className }: Props) {
  // Calls fill from the right (reading inward toward the strike), puts from the
  // left. Clamp so a rounding overshoot never spills past the track.
  const pct = value != null && max > 0 ? Math.min(100, (value / max) * 100) : 0;

  return (
    <span className={cx(s.track, className)}>
      <span className={cx(s.fill, s[side])} style={{ width: `${pct}%` }} />
    </span>
  );
}

// frontend/src/routes/(terminal)/option-chain/components/OIBar.svelte
<script lang="ts">
  import type { Side } from '../chain-model';

  interface Props {
    value?: number | undefined;
    max: number;
    side: Side;
  }

  let { value, max, side }: Props = $props();

  // Calls fill from the right (reading inward toward the strike), puts from the
  // left. Clamp so a rounding overshoot never spills past the track.
  const pct = $derived(value != null && max > 0 ? Math.min(100, (value / max) * 100) : 0);
</script>

<span class="track">
  <span class="fill {side}" style="width: {pct}%"></span>
</span>

<style>
  .track {
    display: block;
    position: relative;
    height: 0.375rem;
    width: 5rem;
    border-radius: 999px;
    background: var(--mc-border);
  }

  .fill {
    position: absolute;
    top: 0;
    height: 100%;
    border-radius: 999px;
  }

  .fill.ce {
    right: 0;
    background: var(--mc-bullish);
  }

  .fill.pe {
    left: 0;
    background: var(--mc-bearish);
  }
</style>
