// frontend/src/routes/(terminal)/settings/profile/+page.svelte
<script lang="ts">
  import { session } from '$contexts/identity/session.svelte';

  const user = $derived(session.user);

  const memberSince = $derived(
    user?.created_at
      ? new Date(user.created_at).toLocaleDateString(undefined, {
          year: 'numeric',
          month: 'long',
          day: 'numeric'
        })
      : '—'
  );

  const loginMethod = $derived(
    user?.linked_providers?.includes('google') && user?.has_password
      ? 'Password & Google'
      : user?.linked_providers?.includes('google')
        ? 'Google'
        : user?.has_password
          ? 'Password'
          : '—'
  );
</script>

<svelte:head>
  <title>Personal Info · Settings · MarketCompass</title>
</svelte:head>

<h1>Personal Info</h1>

<div class="row first">
  <div class="copy">
    <p class="label">Display name</p>
    <p class="hint">The name shown across the terminal.</p>
  </div>
  <span class="value">{user?.display_name || '—'}</span>
</div>

<div class="row">
  <div class="copy">
    <p class="label">Email address</p>
    <p class="hint">The email address associated with your account.</p>
  </div>
  <div class="value-stack">
    <span class="value mono">{user?.email || '—'}</span>
    {#if user && !user.email_verified}
      <span class="unverified">Unverified</span>
    {/if}
  </div>
</div>

<div class="row">
  <div class="copy">
    <p class="label">Phone number</p>
    <p class="hint">Also usable to sign in, alongside your email address.</p>
  </div>
  <span class="value mono">{user?.phone || '—'}</span>
</div>

<div class="row">
  <div class="copy">
    <p class="label">Sign-in method</p>
    <p class="hint">How you authenticate into MarketCompass.</p>
  </div>
  <span class="value">{loginMethod}</span>
</div>

<div class="row">
  <div class="copy">
    <p class="label">Member since</p>
    <p class="hint">When your account was created.</p>
  </div>
  <span class="value">{memberSince}</span>
</div>

<div class="row">
  <div class="copy">
    <p class="label">Status</p>
    <p class="hint">Your account's current standing.</p>
  </div>
  <span class="value capitalize">{user?.status.replace('_', ' ') || '—'}</span>
</div>

<style>
  h1 {
    margin: 0 0 var(--mc-space-4);
    font-size: var(--mc-text-xl);
    font-weight: 700;
    letter-spacing: -0.01em;
  }

  .row {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: var(--mc-space-6);
    margin: 0 calc(-1 * var(--mc-space-4));
    padding: var(--mc-space-6) var(--mc-space-4);
    border-top: 1.5px solid var(--mc-border-strong);
    border-radius: var(--mc-radius);
    transition: background var(--mc-duration-fast) ease;
  }

  .row:hover {
    background: var(--mc-surface-raised);
  }

  .row.first {
    margin-top: var(--mc-space-4);
    border-top: none;
  }

  .copy {
    min-width: 0;
    max-width: 32rem;
  }

  .label {
    margin: 0;
    font-size: var(--mc-text-base);
    font-weight: 700;
  }

  .hint {
    margin: var(--mc-space-2) 0 0;
    font-size: var(--mc-text-sm);
    line-height: 1.6;
    color: var(--mc-text-muted);
  }

  .value {
    flex: none;
    font-size: var(--mc-text-base);
    font-weight: 600;
    color: var(--mc-text);
    text-align: right;
  }

  .value.mono {
    font-family: var(--mc-font-mono);
    font-weight: 500;
  }

  .value.capitalize {
    text-transform: capitalize;
  }

  .value-stack {
    display: flex;
    flex-direction: column;
    align-items: flex-end;
    gap: 0.1875rem;
  }

  .unverified {
    font-size: var(--mc-text-xs);
    font-weight: 700;
    color: var(--mc-danger);
  }

  @media (max-width: 30rem) {
    .row {
      flex-direction: column;
      align-items: flex-start;
      gap: var(--mc-space-2);
    }

    .value,
    .value-stack {
      text-align: left;
      align-items: flex-start;
    }
  }
</style>

// frontend/app/routes/terminal/settings/profile.tsx
import { useUser } from '$contexts/identity/use-session';
import { cx } from '$shared/ui/cx';
import s from './profile.module.css';
import type { Route } from './+types/profile';

export const meta: Route.MetaFunction = () => [
  { title: 'Personal Info · Settings · MarketCompass' }
];

export default function SettingsProfile() {
  const user = useUser();

  const memberSince = user?.created_at
    ? new Date(user.created_at).toLocaleDateString(undefined, {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      })
    : '—';

  const loginMethod =
    user?.linked_providers?.includes('google') && user?.has_password
      ? 'Password & Google'
      : user?.linked_providers?.includes('google')
        ? 'Google'
        : user?.has_password
          ? 'Password'
          : '—';

  return (
    <>
      <h1 className={s.title}>Personal Info</h1>

      <div className={cx(s.row, s.first)}>
        <div className={s.copy}>
          <p className={s.label}>Display name</p>
          <p className={s.hint}>The name shown across the terminal.</p>
        </div>
        <span className={s.value}>{user?.display_name || '—'}</span>
      </div>

      <div className={s.row}>
        <div className={s.copy}>
          <p className={s.label}>Email address</p>
          <p className={s.hint}>The email address associated with your account.</p>
        </div>
        <div className={s.valueStack}>
          <span className={cx(s.value, s.mono)}>{user?.email || '—'}</span>
          {user && !user.email_verified ? <span className={s.unverified}>Unverified</span> : null}
        </div>
      </div>

      <div className={s.row}>
        <div className={s.copy}>
          <p className={s.label}>Phone number</p>
          <p className={s.hint}>Also usable to sign in, alongside your email address.</p>
        </div>
        <span className={cx(s.value, s.mono)}>{user?.phone || '—'}</span>
      </div>

      <div className={s.row}>
        <div className={s.copy}>
          <p className={s.label}>Sign-in method</p>
          <p className={s.hint}>How you authenticate into MarketCompass.</p>
        </div>
        <span className={s.value}>{loginMethod}</span>
      </div>

      <div className={s.row}>
        <div className={s.copy}>
          <p className={s.label}>Member since</p>
          <p className={s.hint}>When your account was created.</p>
        </div>
        <span className={s.value}>{memberSince}</span>
      </div>

      <div className={s.row}>
        <div className={s.copy}>
          <p className={s.label}>Status</p>
          <p className={s.hint}>Your account&apos;s current standing.</p>
        </div>
        <span className={cx(s.value, s.capitalize)}>{user?.status.replace('_', ' ') || '—'}</span>
      </div>
    </>
  );
}
