// frontend/app/lib/shared/ui/PasswordField.tsx
import { useState } from 'react';
import IconEye from './icons/IconEye';
import IconEyeOff from './icons/IconEyeOff';
import IconLock from './icons/IconLock';
import s from './PasswordField.module.css';
import TextField from './TextField';

interface Props {
  label?: string | undefined;
  value: string;
  onValueChange?: ((value: string) => void) | undefined;
  placeholder?: string | undefined;
  error?: string | undefined;
  autocomplete?: 'current-password' | 'new-password' | undefined;
  required?: boolean | undefined;
  /** Forwarded to the field wrapper — see TextField. */
  className?: string | undefined;
}

export default function PasswordField({
  label = 'Password',
  value,
  onValueChange,
  placeholder = 'Enter your password',
  error,
  autocomplete = 'current-password',
  required = false,
  className
}: Props) {
  const [revealed, setRevealed] = useState(false);

  return (
    <TextField
      label={label}
      value={value}
      onValueChange={onValueChange}
      error={error}
      placeholder={placeholder}
      required={required}
      className={className}
      autoComplete={autocomplete}
      type={revealed ? 'text' : 'password'}
      icon={<IconLock />}
      trailing={
        <button
          type="button"
          className={s.toggle}
          onClick={() => setRevealed((current) => !current)}
          aria-pressed={revealed}
          aria-label={revealed ? 'Hide password' : 'Show password'}
          tabIndex={-1}
        >
          {revealed ? <IconEye /> : <IconEyeOff />}
        </button>
      }
    />
  );
}

// frontend/src/lib/shared/ui/PasswordField.svelte
<script lang="ts">
  import TextField from './TextField.svelte';
  import IconLock from './icons/IconLock.svelte';
  import IconEye from './icons/IconEye.svelte';
  import IconEyeOff from './icons/IconEyeOff.svelte';

  interface Props {
    label?: string;
    value: string;
    placeholder?: string;
    error?: string | undefined;
    autocomplete?: 'current-password' | 'new-password';
    required?: boolean;
  }

  let {
    label = 'Password',
    value = $bindable(''),
    placeholder = 'Enter your password',
    error = undefined,
    autocomplete = 'current-password',
    required = false
  }: Props = $props();

  let revealed = $state(false);
</script>

<TextField
  {label}
  bind:value
  {error}
  {placeholder}
  {required}
  {autocomplete}
  type={revealed ? 'text' : 'password'}
>
  {#snippet icon()}
    <IconLock />
  {/snippet}

  {#snippet trailing()}
    <button
      type="button"
      class="toggle"
      onclick={() => (revealed = !revealed)}
      aria-pressed={revealed}
      aria-label={revealed ? 'Hide password' : 'Show password'}
      tabindex={-1}
    >
      {#if revealed}
        <IconEye />
      {:else}
        <IconEyeOff />
      {/if}
    </button>
  {/snippet}
</TextField>

<style>
  .toggle {
    display: inline-flex;
    align-items: center;
    padding: var(--mc-space-1);
    background: none;
    border: none;
    color: var(--mc-text-subtle);
    cursor: pointer;
  }

  .toggle:hover {
    color: var(--mc-text-muted);
  }
</style>
